// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// gamma_helper
NumericMatrix gamma_helper(NumericMatrix Sr, NumericVector ar, NumericMatrix Or);
RcppExport SEXP SimNashPrice_gamma_helper(SEXP SrSEXP, SEXP arSEXP, SEXP OrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Sr(SrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ar(arSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Or(OrSEXP);
    rcpp_result_gen = Rcpp::wrap(gamma_helper(Sr, ar, Or));
    return rcpp_result_gen;
END_RCPP
}
// envelope_helper
List envelope_helper(NumericMatrix Sr, NumericVector ar);
RcppExport SEXP SimNashPrice_envelope_helper(SEXP SrSEXP, SEXP arSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Sr(SrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ar(arSEXP);
    rcpp_result_gen = Rcpp::wrap(envelope_helper(Sr, ar));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"SimNashPrice_gamma_helper", (DL_FUNC) &SimNashPrice_gamma_helper, 3},
    {"SimNashPrice_envelope_helper", (DL_FUNC) &SimNashPrice_envelope_helper, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_SimNashPrice(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
