// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// gamma_helper
NumericMatrix gamma_helper(NumericMatrix Sr, NumericVector ar, NumericMatrix Or);
RcppExport SEXP SimNashPrice_gamma_helper(SEXP SrSEXP, SEXP arSEXP, SEXP OrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Sr(SrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ar(arSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Or(OrSEXP);
    rcpp_result_gen = Rcpp::wrap(gamma_helper(Sr, ar, Or));
    return rcpp_result_gen;
END_RCPP
}
