Market <- R6::R6Class(
  "mkt",
  public = list(
    initialize = mkt_construct,
    Ownership = Ownership,
    getPotentialProds = getPotential_products,
    getMarket = getMarket,
    getProfits = getProfits,
    getMarkups = getMarkups,
    inferMarkups = inferMarkups,
    getCosts = getCosts,
    getPrices = getPrices,
    getShares = getShares,
    getMeanUs = getMeanUs,
    getWhichFirm = getWhichFirm,
    getDs_list = getDs,
    ZFP = ZFP,
    setPrices = setPrice,
    setShares = setShares,
    setShocks = setShocks,
    setActiveProds = setActiveProds,
    updateActivity = updateActivity
  ),
  private = list(
    Potential_products = NULL,
    firm_names = NULL,
    O_mat = NULL,
    A_mat = NULL,
    Which_is_firm_mat = NULL,
    own_vec = NULL,
    active_products = NULL,
    prices = NULL,
    shares = NULL,
    Lambda = NULL,
    Gamma = NULL,
    Ds = NULL,
    market_size = NULL,
    Jt = NULL,
    u_opt_out = NULL,
    costs = NULL,
    deltas = NULL,
    num_firms = NULL,
    are_prods_active = FALSE,
    cost_shocks = NULL,
    taste_shocks = NULL
  )
)
