# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gamma_helper <- function(Sr, ar, Or) {
    .Call('SimNashPrice_gamma_helper', PACKAGE = 'SimNashPrice', Sr, ar, Or)
}

